import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GoodHive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div>
          <button>Metamask</button>
        </div>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Looking for a Talent
        </h1>

        <form>
          <label>Skill</label>
          <input type="text" />
          <label>Location</label>
          <input type="text" />
          <button type="submit" onClick={e => e.preventDefault()}>Search</button>
        </form>
      </main>

      <footer className={styles.footer}>
        GoodHive 2022
      </footer>
    </div>
  )
}
